### Basic of Numpy

In [ ]:
# Import numpy and check its version

import numpy as np

print(np.__version__)              # version

arr = np.array([1,2,3])            # numpy array
print(arr)

arr2 = np.array((1, 2, 3, 4, 5))
print(arr2)

print(type(arr))                   # Data

### Dimensions of Array

In [40]:
# 0D Array

a0d = np.array(10)
print("__________0D__________")
print(a0d)
print("Dimension : ",a0d.ndim)

# 1D Array

a1d = np.array([1,2,3])
print("__________1D__________")
print(a1d)
print("Dimension : ",a1d.ndim)

# 2D Array

a2d = np.array([[1,2,3],[4,5,6]])
print("__________2D__________")
print(a2d)
print("Dimension : ",a2d.ndim)

# 3D Array

a3d = np.array([[[1,2,3],[4,5,6]],[[7,8,9],[2,3,4]]])
print("__________3D__________")
print(a3d)
print("Dimension : ",a3d.ndim)


__________0D__________
10
Dimension :  0
__________1D__________
[1 2 3]
Dimension :  1
__________2D__________
[[1 2 3]
 [4 5 6]]
Dimension :  2
__________3D__________
[[[1 2 3]
  [4 5 6]]

 [[7 8 9]
  [2 3 4]]]
Dimension :  3


In [41]:
c = np.array([[1, 2], [3, 4]], dtype=complex)
c

array([[1.+0.j, 2.+0.j],
       [3.+0.j, 4.+0.j]])

In [52]:
c = np.arange(15).reshape(3, 5)
print(c)
print(c.shape)
print(c.ndim)
print(c.size)
print(c.itemsize)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]
(3, 5)
2
15
8
